version: '3.1'
services:
  order-service:
    build: order-service
    image: order-service-image
    container_name: order-service-container
    depends_on:
      - order-db
    #ports:
    #  - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=order
      - SPRING_DATASOURCE_PASSWORD=order

  order-db:
    image: postgres:14.4-alpine
    container_name: order-db-container
    volumes:
      - order-db:/var/lib/postgresql/data
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=order
      - POSTGRES_PASSWORD=order

volumes:
  order-db: