eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
        service-url:
            defaultZone: http://localhost:8761/eureka
logging:
    level:
        com:
            netflix:
                discovery: 'OFF'
                eureka: 'OFF'
    pattern:
        console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'
server:
    port: 8761
spring:
    application:
        name: eureka-server
